FROM golang:1.25-alpine3.22 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

# LICENSE_PUBLIC_KEY is injected using -ldflags at build time
ARG LICENSE_PUBLIC_KEY
RUN go build -o /app/server -ldflags="-X main.LicensePublicKey=$LICENSE_PUBLIC_KEY" cmd/server/main.go

FROM alpine:latest

WORKDIR /app

# Install tzdata for Asia/Jakarta time zone
RUN apk add --no-cache tzdata curl

COPY --from=builder /app/server .

CMD ["/app/server"]
