DROP TABLE IF EXISTS environments;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS folders;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS users;
