ALTER TABLE collections DROP COLUMN IF NOT EXISTS confluence_page_id;
DELETE FROM system_settings WHERE key IN ('CONFLUENCE_ENABLED', 'CONFLUENCE_BASE_URL', 'CONFLUENCE_PERSONAL_TOKEN', 'CONFLUENCE_SPACE_KEY');
