name: Build/Release Wapify Desktop

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # Menggunakan runner milik sendiri (Mac/STB) agar 100% GRATIS
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
          cache-dependency-path: apps/desktop/package-lock.json

      - name: Install Dependencies
        run: |
          cd apps/desktop
          npm install --ignore-scripts

      - name: Rebuild Native Modules
        run: |
          cd apps/desktop
          npx @electron/rebuild --only keytar
        shell: bash

      - name: Build Application
        run: |
          cd apps/desktop
          npm run build
        env:
          VITE_APP_VERSION: ${{ github.ref_name }}

      - name: Publish Release to Public Repo
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          repository: abdullahPrasetio/wapify-desktop-releases
          package_root: apps/desktop
          release: true
          # Hanya tambahkan flag arsitektur tambahan
          args: --universal --win --x64 --arm64 --linux --x64 --arm64
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
